### ISSUE TITLE
gaussian likelihood

### ISSUE THREAD

**Issue by el3ment** [corenel/pytorch-glow#1]
I don't understand why you are dividing by the exp in this line:

https://github.com/corenel/pytorch-glow/blob/master/network/module.py#L450

it seems like this is incorrect if it is supposed to be the log of a gaussian

**Comment by corenel** [comment]
`logs` represents `log(sigma)`
Computing the negative log-likelihood of a Gaussian distribution needs `S` where `S_{ii}=\sigma^2`
The equation is like it in [this page](http://docs.chainer.org/en/stable/reference/generated/chainer.functions.gaussian_nll.html).

**Comment by el3ment** [comment]
I believe everything except the `/ torch.exp(2. * logs)`  which isn't part of the log gaussian formula

**Comment by el3ment** [comment]
log(exp(x)) == exp(log(x)) -- by making that switch, you can parameterize everything in terms of log(s)
